document.getElementById('00').addEventListener('click', function() {
    document.getElementById('output').textContent = 'You are humble, self-effacing, industrious, and practical. While being kind and sympathetic, you are also a quick thinker. You tend to be a perfectionist and this can cause stress and tension. You have got strong negotiation powers and utilizing this skill, you win debates and others hearts. You are highly committed and are diligent. This reflects in office work. However, being stubborn can affect the appraisals and promotions at the workplace.';
});

document.getElementById('01').addEventListener('click', function() {
    document.getElementById('output').textContent = ' Your charming personality will appeal to people around you. There is confidence in you which will work for benefit while venturing new assignments. You have a strong will and desire for corporate stability. Normally you are prone to anger but once you lose it, you go terrifying. This needs to be checked as can hamper relations. For you, integrity is higher than anything and you do hard labor to achieve what you desire. You are fortunate in financial matters. You are highly determined and normally get into trouble due to this. Sometimes you are misunderstood to be having a laidback attitude but it is not. You are mostly driven by intellectual and analytical nature.';
});
document.getElementById('02').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are intelligent and a quick learner. You have strong analytical skills that work for benefit in office and personal life. Being a Gemini, you have an unreserved and childlike curiosity, which makes you raise questions. While being a good observer, you also entertain people around. The ability to understand a person’s in and out is a great trait. Being a good communicator and listener will help in professional life, especially while in a team. Being joyful and extroverted, you have no issues in mixing up with people from different spheres and also have the knack of bringing people together.';
});
document.getElementById('03').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are empathetic, sympathetic, and compassionate, and sometimes even psychic when it comes to relations. You’re enthusiastic, warm and you have a hard-wired urge to protect the underdog, or the bullied. You are someone whom others would prefer like having a big brother – always protective. In a romantic relationship, you want the partner to respect and give attention. Life will be packed with many challenges and you may be extra cautious while trusting others as even minor issues can hurt you deeply.';
});
document.getElementById('04').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are brave and always are ready to conquer. You are not worried about challenges as you have the willpower and confidence to overcome them. If you make a decision, you will go all the way to accomplish it. Compassion, consciousness, drive, and natural leadership are the four main attributes of Leos. As you are conscious about time and give respect to money and people, you are welcome everywhere. As you are honest and loyal, professional life will be successful. However, innate self-confidence and boldness can often end up in problematic decision making and this can hamper success in life and profession.';
});
document.getElementById('05').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are extrovert, cosy, and friendly. You always try to attain balance in everything and are concerned about harmony, justice, and peace in this world. While being tactful, pleasing, and diplomatic, you always fit in anytime and any place. You are charming, intelligent, and frank. You are a firm believer in networking and you prefer to be the center of attraction. You love to think, analyze, ponder and dissect stuff that makes you a champion procrastinator. They love to take an objective viewpoint, find the fairest solution to any issue, and enjoy learning new information. They need mental stimulation. Instead of constantly seeking outside perspectives, you prefer to develop your own intuition.';
});
document.getElementById('06').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are mysterious because you think a lot and are secretive and passionate. You are highly emotional and always look for a connection. As you are passionate, you pay special care for friends and near ones. While being a demanding personality, there is also a mystery surrounding you. When you keep your heart on something, there is no looking back. No danger can stop you from achieving something you are passionate about. Being honest, you go to any extent to help others but can sometimes be deceived by near ones.';
});
document.getElementById('07').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are optimistic, hilarious, honest, fair-minded, and intelligent. You are spontaneous and love being with friends. However, the worst side is that you get bored easily and are commitment-phobic. You aren’t afraid of exploring new terrains and taking up new ventures. Your quest for new knowledge has no bounds. You are highly creative and are an entertainer. This works in benefit at the professional scene.';
});
document.getElementById('08').addEventListener('click', function() {
    document.getElementById('output').textContent =' You are emotional, sensitive, kind, compassionate, and thinking. You are drawn to art and beauty and are also quite intuitive, creative, empathetic, and selfless. You love to help others and go to any extent to support the needy ones. While being selfless and soft, you are also gentle with people while dealing. However, escapism is a negative trait as you become idealistic about everything that life has on offer. In addition, you also tend to lose enthusiasm very fast and get snubbed at defeats. While laziness is a major trait of yours, you are also a firm believer of unrealistic dreams that can cause serious setbacks in life.';
});
document.getElementById('09').addEventListener('click', function() {
    document.getElementById('output').textContent ='You are an upfront person and do not practice shady business. You speak on the face and never pretend things. Some people may find you aloof or cold but the truth is that you prefer keeping emotions down. You share the moon sign with many revolutionary people who believed in the transformation of this world. You too are rebellious and believe you can change the world in many aspects. This makes you innovative in concepts. For you, freedom is the most vital aspect, and would not tolerate someone curbing your rights.';
});

